apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deploymentName }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.appName }}
    spec:
      containers:
        - name: {{ .Values.backend.appName }}
          image: {{ .Values.backend.image }}
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_SERVICE_URL
              value: {{ .Values.redis.serviceURL }}
