apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.frontend.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
