apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName }}
spec:
  selector:
    app: {{ .Values.redis.appName }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
